theme: jekyll-theme-minimal
title: Agent-Based Modeling for Archaeology
logo: https://images.squarespace-cdn.com/content/v1/5d420e5d999d0200013d33c3/1624392525207-7VAO0EMDZHADE2EWOREC/ke17ZwdGBToddI8pDm48kG8UBA41wS1R7AvxRh_wkwNZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpze26jBNtoki230X-gM1LVvNyVntGK3L31vDiVkQOhNOK2f7ze3Qo1Gqhr7QittBso/ABMA-cover-slice-600.png?format=2500w
show_downloads: false
